name: 'Push to Balena with tag'
branding:
  color: "yellow"
  icon: "box"
description: 'Push your code to BalenaCloud using balena-cli'
inputs:
  api-token:
    description: 'BalenaCloud API Key'
    required: true
  application-name:
    description: "The name of the BalenaCloud Application that you'll be pushing to"
    required: true
  application-path:
    description: "Optional. Provide a subfolder path to your BalenaCloud application, example: ./balena-wpe"
    default: "."
  release-tag-key:
    description: "Optional. Provide a release tag key, example: version"
    default: ""
  release-tag-value:
    description: "Optional. Provide a release tag value, example: 1.0"
    default: ""
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    API_TOKEN: ${{ inputs.api-token }}
    APPLICATION_NAME: ${{ inputs.application-name }}
    APPLICATION_PATH: ${{ inputs.application-path }}
    RELEASE_TAG_KEY: ${{ inputs.release-tag-key }}
    RELEASE_TAG_VALUE: ${{ inputs.release-tag-value }}
